### ISSUE TITLE
Command line arguments (file paths) with spaces

### ISSUE THREAD

**Issue by fligi7** [strozfriedberg/ntfs-linker#1]
It appears that the command-line executable doesn't interpret file paths with spaces, whether quoted or not. Is it possible to build in this functionality? I'm very eager to try out the tool.

**Comment by zweger** [comment]
I'm unable to reproduce this behavior. What platform are you running on? Can you give an example usage which fails?

**Comment by fligi7** [comment]
Perhaps it's an argument structure issue, but I'm just following the examples on http://strozfriedberg.github.io/ntfs-linker/. 

Running on Windows Server 2008 R2. Command issued as seen below:

`ntfs-linker.exe --image "W:\\Name of Image.E01" --output C:\Users\Name\Desktop`

> Error: did not understand arguments

**Comment by zweger** [comment]
Ah! It seems the github.io page had gotten out of date. I've updated the docs (it may take a little while to sync).

You need to specify `--ntfs-dir`, even if you've specified `--image`. The ntfs-dir parameter is where ntfs-linker looks for the `$MFT`, `$J`, `$LogFile` files (I believe the documentation for how ntfs-linker interprets that folder structure is correct). If `--image` is specified (it's optional), then those files are first copied out prior to being parsed.

**Comment by fligi7** [comment]
Understood. Working now.

However, I believe the command structure on the page still needs to be updated to the following:

`ntfs-linker.exe <ntfs_dir> --image /path/to/image.E01 --output /path/to/output/`

I don't see any `--input` argument in the current executable's argument options.

**Comment by zweger** [comment]
Thanks. I thought I had updated the page but I guess it didn't go through. Should be good now!

**Comment by fligi7** [comment]
Looks good. 

However, we have another issue. It appears that it does find all 4 VSS stores in the provided image but the extracted MFT, J, and UsnJrnl files are all 0kb. Now, this image is a split E01 containing multiple ~4GB segments. Is this possibly the issue or could it be something else?

**Comment by zweger** [comment]
NTFS-Linker does support split E01 images, so that's not the issue. What's the console output? Have you verified in other tools these files exist/are readable?

**Comment by fligi7** [comment]
All have $Logfile with data, $UsnJrnl with no data, and none have $MFT, only $MFTMirr. 

So, that explains why $J and $MFT are zero, but not why $Logfile is. 

At any rate, may not matter as you can't correlate 3 files when 2 are non-existent/zero. Perhaps it would make sense to build in some error-checking for non-existent/zero size files, alert and not export them, and exit gracefully when the program does not have enough data to perform its intended operation instead of just causing a hard app crash. 

Just suggestions, though. I know building an app like this isn't easy and you didn't sign up to be accountable for every possible issue. It looks like a great tool that I'm eager to see in action once I have a system with the appropriate data.
